### PR TITLE
[WIP] Keys per app with the exception of prod env.

### PR DESCRIPTION
**Pull request by ltsampros**

### CODE REVIEW

**Comment by niallcreech** [comment]
Can we hold off on this until we have a good reason to share cryptographic keys across environments beyond our AWS supplier problem? Projects may have other environments that require that level of separation so we'd need to research this. This is just to make sure we're not rushing through architectural security changes on the basis of failed support levels  from amazon

**Comment by niallcreech** [comment]
Note, the above doesnt mean its a bad idea, just that although the code change is trivial it might be a change that requires more consultation and review

**Comment by niallcreech** [comment]
Security-wise what I'm thinking of is something like the scenario,
1. Project creates dev, staging, unsecure, test, training and prod. Prod has its own key protecting its config, all the rest share a key. 
2. Project create 'secure' environment, to be even more secure than prod! applying all the hardening config settings they could muster
3.The supposedly 'secure' environment is now tied to the security of the weakest link amongst all other environments.
4. Someone compromises dev/staging/unsecure/test/training/etc/etc environment

Although we could blacklist environments from having their own key instead, I'm just not sure this actually improves things too much. Is 'demo' == 'prod'? is 'training' == 'prod'? In some cases they very much are, in many projects not.

Fundamentally we'd be making this change purely based on the poor quality delays in AWS supports actions rather than wanting to do it because it adds something we want. Or saving a few tens of pounds a month on a tens of thousands of pounds monthly bill. A reduction in security would concern and cost us much more. If this is something we want to press ahead with, I'd suggest talking to our security/pentesters to see what the actual implications are.

**Comment by ltsampros** [comment]
I agree with you on all fronts. However, it's an 'acceptable' workaround for moments when our AWS key limit is reached.

I added WIP to the title as this was the original intention.

**Comment by niallcreech** [comment]
Cool, nice to keep on hand for crisis. Hopefully we can get good AWS support soon and there will be no more tears :)

**Pull request closed without merging**
