### PR TITLE
Fix for not installing boto

### PR DESCRIPTION
**Pull request by mattmb**
We need boto installed because we use it in template deploy to convert the AWS tags to salt grains.

### CODE REVIEW

**Comment by stuartornum** [comment]
Why don't we just run the commands inside the .sh instead of maintaining the .sh file - also, didnt we just remove this .sh file

**Comment by mattmb** [comment]
Yeah, the call to it was removed but it breaks the script in template deploy that sets grains from tags because we need boto. Happy to have it all in one script but we can do that in a separate PR.

**Comment by ashb** [comment]
If boto 2.20.1 is new enough then we can install the "python-boto" package.

We need to move away from pulling a script from master off github - it makes backwards compatibility significantly harder. Either we should `put()` the file with fabric or invoke the commands we want directly (which I think is my preferred method here)

**Comment by mattmb** [comment]
Yeah agree that we shouldn't just pull stuff from master. Really only created this because it was blocking me. Will tidy up some point soon.

**Comment by ashb** [comment]
Matt and I chatted and we think this might be easier done via installing as a deb package. Testing this now: https://github.com/ministryofjustice/bootstrap-salt/compare/fix/missing-boto-via-package

**Comment by mattmb** [comment]
Closed in favour of #21

**Pull request closed without merging**
